name: "New Feature (Item) Support Request"
description: Request support for a new feature
title: "[Item] "
labels: ["new-item"]
assignees: ["chasarooniZ"]
body:
  - type: input
    id: feature_link
    attributes:
      label: "Feature Link"
      description: "Please provide a link to the feature you want (documentation, example, reference, etc.)"
      placeholder: "https://example.com/feature-documentation"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a detailed description of the feature request. Include information about automation, use cases, expected behavior, etc."
      placeholder: "Describe the feature you'd like to see implemented..."
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: "Pre-submission Checklist"
      description: "Please confirm you have completed the following:"
      options:
        - label: "I have verified that this feature is not already available in the module"
          required: true
        - label: "I have searched existing issues to ensure this request hasn't been made before"
          required: true
